### ISSUE TITLE
arka uç çökmesi

### ISSUE THREAD

**Issue by slarikan** [pisilinux/PisiLinux#372]
bilgisayar açıldığında sağalt tarafta şu uyarı geliyor
KDE Güç Yönetimi Sistemi başlatılamadı. Arka uç şu hatayı bildirdi: Kullanılabilir bir Güç Yönetimi arka ucu eklentisi yok. Yeniden kurulum bu sorunu çözebilir. Lütfen sistem yapılandırmanızı kontrol edin

**Comment by ertugerata** [comment]
http://sudrap.org/paste/text/510219/ dmesg
http://sudrap.org/paste/text/510227/ pisi hs

**Comment by groni** [comment]
The same happend here:
http://www.sudrap.org/paste/text/511213/
http://www.sudrap.org/paste/text/511217/

**Comment by slarikan** [comment]
upower den kaynaklanıyormuş slack ta anlatılmış çözüm için [28 Ocak 2015 Çarşamba] [19:08:26] <suvari>
sudo pisi bi -dvy https://github.com/hknyldz/PisiLinux/raw/3142524a8a12aa70aac2eb1cf705a9b8f13add14/main/hardware/powermanagement/upower/pspec.xml
paketin derlenerek kurulması gerekiyor
