### ISSUE TITLE
kmod error in mudur.log 

### ISSUE THREAD

**Issue by ertugerata** [pisilinux/PisiLinux#562]
in /var/log/mudur.log 

[1427650101.549] Mar 29 20:28:21 Errors during tmpfiles creation.
       c! - wrong type in file: /run/tmpfiles.d/kmod.conf
       c! - wrong type in file: /run/tmpfiles.d/kmod.conf
       c! - wrong type in file: /run/tmpfiles.d/kmod.conf
       c! - wrong type in file: /run/tmpfiles.d/kmod.conf
       c! - wrong type in file: /run/tmpfiles.d/kmod.conf
       c! - wrong type in file: /run/tmpfiles.d/kmod.conf
       c! - wrong type in file: /run/tmpfiles.d/kmod.conf
       c! - wrong type in file: /run/tmpfiles.d/kmod.conf
       c! - wrong type in file: /run/tmpfiles.d/kmod.conf
       c! - wrong type in file: /run/tmpfiles.d/kmod.conf
       c! - wrong type in file: /run/tmpfiles.d/kmod.conf

is common bug in debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780263
 is fixed in gentoo 
https://gitweb.gentoo.org/proj/openrc.git/diff/init.d/tmpfiles.dev.in?id=3c5dc0ec7774a72e243da43ac5180ea36a311ad8

diff --git a/init.d/tmpfiles.dev.in b/init.d/tmpfiles.dev.in
index 3566928..c809bf9 100644
--- a/init.d/tmpfiles.dev.in
+++ b/init.d/tmpfiles.dev.in
@@ -14,7 +14,7 @@ depend()
start()
{
    ebegin "setting up tmpfiles.d entries for /dev"
-    @LIBEXECDIR@/sh/tmpfiles.sh --prefix=/dev --create ${tmpfiles_opts}
+    @LIBEXECDIR@/sh/tmpfiles.sh --prefix=/dev --create --boot ${tmpfiles_opts}

fixed in systemd too; 

ertugrul [7:31 PM]7:31
--- a/units/systemd-tmpfiles-setup-dev.service.in
+++ b/units/systemd-tmpfiles-setup-dev.service.in
@@ -17,4 +17,4 @@ ConditionCapability=CAP_SYS_MODULE
[Service]
Type=oneshot
RemainAfterExit=yes
-ExecStart=@rootbindir@/systemd-tmpfiles --prefix=/dev --create
+ExecStart=@rootbindir@/systemd-tmpfiles --prefix=/dev --create --boot

**Comment by marcin-** [comment]
mudur does not recognize "!" char. I didn't add such functionality, but seems it should be easy to fix.

**Comment by marcin-** [comment]
as I said it is very easy to fix
here is patch for mudur -> https://raw.githubusercontent.com/marcin-/scripts/master/patches/mudur/boot_option.patch
