### ISSUE TITLE
move to ConsoleKit2 // ConsoleKit2 ye geçmemiz lazım 

### ISSUE THREAD

**Issue by ertugerata** [pisilinux/PisiLinux#570]
http://www.freedesktop.org/wiki/Software/ConsoleKit/ 
ConsoleKit is a framework for defining and tracking users, login sessions, and seats.
ConsoleKit is currently not actively maintained. The focus has shifted to the built-in seat/user/session management of Software/systemd called systemd-logind!

ConsoleKit2 is fork ConsoleKit, in development release https://github.com/ConsoleKit2/ConsoleKit2

manjaro
https://github.com/manjaro/packages-openrc use this package. 
https://github.com/manjaro/packages-openrc/blob/master/consolekit/PKGBUILD ..

**Comment by ertugerata** [comment]
@vedat bey zaten yapmis. Ama master.zip source verilmis umariz derlenir.

**Comment by Vedat** [comment]
Kimsiniz

iPhone'umdan gönderildi

3 Nis 2015 tarihinde 16:48 saatinde, Ertuğrul Erata <notifications@github.com> şunları yazdı:
