### ISSUE TITLE
Pisilinux 2.0 beta2 30Agu konqueror hatası

### ISSUE THREAD

**Issue by samettirpan** [pisilinux/PisiLinux#801]
Canlı Cd ortamında konqueror penceresi ekranı kaplayınca çöküyör

**Comment by ertugerata** [comment]
1. pisi-2.0 ile ilgili hatalar https://github.com/pisilinux/main/issues buradan takip edilmektedir. 
2. Pisi-2.0 RC sürümünü yalı içerecek şekilde https://github.com/pisilinux/main/releases de görülebileceği gibi 5 Nisan 2017 de çıkartmıştır.
